exclude: '^$'
fail_fast: false
repos:
 -  repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    - id: trailing-whitespace
    - id: check-merge-conflict
 - repo: git://github.com/antonbabenko/pre-commit-terraform
   rev: v1.45.0
   hooks:
     - id: terraform_fmt
     - id: terraform_docs
       args: ['--args=document']
     - id: terraform_validate
